name: mobile
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.3

dependencies:
  flutter:
    sdk: flutter
  
  # --- Network & UI ---
  dio: ^5.4.0
  flutter_riverpod: ^2.4.9
  go_router: ^13.0.0
  google_fonts: ^6.1.0
  cupertino_icons: ^1.0.8

  # --- DATABASE ---
  drift: ^2.14.0
  sqlite3_flutter_libs: ^0.5.18
  path_provider: ^2.1.1
  path: ^1.8.3

  # --- CHART & UTILS ---
  fl_chart: ^0.66.0
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

  # --- CODE GENERATOR ---
  build_runner: ^2.4.8
  drift_dev: ^2.14.0

flutter:
  uses-material-design: true